-- Fix GMB Reviews table - use DATETIME instead of TIMESTAMP for review_date
CREATE TABLE IF NOT EXISTS gmb_reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id INT NOT NULL,
    location_id INT NOT NULL,
    google_review_id VARCHAR(255) NOT NULL,
    reviewer_display_name VARCHAR(255) NULL,
    reviewer_profile_photo_url VARCHAR(500) NULL,
    reviewer_is_anonymous TINYINT(1) DEFAULT 0,
    star_rating TINYINT NOT NULL,
    comment TEXT NULL,
    reply_text TEXT NULL,
    replied_at TIMESTAMP NULL,
    replied_by INT NULL,
    status ENUM('new', 'read', 'responded', 'flagged') DEFAULT 'new',
    is_flagged TINYINT(1) DEFAULT 0,
    flag_reason TEXT NULL,
    sentiment ENUM('positive', 'neutral', 'negative') NULL,
    sentiment_score DECIMAL(3,2) NULL,
    key_topics JSON NULL,
    suggested_response TEXT NULL,
    review_date DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_google_review (location_id, google_review_id),
    INDEX idx_gmb_reviews_location (location_id, status),
    INDEX idx_gmb_reviews_rating (location_id, star_rating),
    FOREIGN KEY (location_id) REFERENCES gmb_locations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
