-- Seed 30 Follow-up Automations
DELETE FROM followup_automations WHERE user_id = 1;

INSERT INTO followup_automations (user_id, name, description, channel, trigger_type, trigger_conditions, action_type, action_config, delay_amount, delay_unit, is_active, priority, created_at, updated_at) VALUES
(1, 'Welcome New Subscribers', 'Send welcome email to new contacts', 'email', 'contact_created', '{"source":"any"}', 'send_email', '{"subject":"Welcome!","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Follow Up After Email Open', 'Send follow-up when email is opened', 'email', 'email_opened', '{}', 'send_email', '{"subject":"Glad you opened!","template_id":null}', 24, 'hours', 1, 5, NOW(), NOW()),
(1, 'Re-engage Non-Openers', 'Resend to contacts who did not open', 'email', 'email_not_opened', '{"days":3}', 'send_email', '{"subject":"Did you miss this?","template_id":null}', 72, 'hours', 1, 3, NOW(), NOW()),
(1, 'Click Follow-Up', 'Follow up when link is clicked', 'email', 'email_clicked', '{}', 'send_email', '{"subject":"Thanks for your interest!","template_id":null}', 1, 'hours', 1, 8, NOW(), NOW()),
(1, 'Bounce Handler', 'Tag bounced contacts', 'email', 'email_bounced', '{}', 'add_tag', '{"tag_name":"bounced"}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Unsubscribe Handler', 'Update status on unsubscribe', 'email', 'email_unsubscribed', '{}', 'update_status', '{"status":"unsubscribed"}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Reply Notification', 'Notify team when contact replies', 'email', 'email_replied', '{}', 'notify_user', '{"message":"Contact replied"}', 0, 'minutes', 1, 9, NOW(), NOW()),
(1, 'Positive Reply Follow-Up', 'Follow up on positive replies', 'email', 'email_replied', '{"sentiment":"positive"}', 'send_email', '{"subject":"Great to hear from you!","template_id":null}', 30, 'minutes', 1, 8, NOW(), NOW()),
(1, 'SMS Welcome', 'Send SMS welcome to mobile contacts', 'sms', 'contact_created', '{"has_phone":true}', 'send_sms', '{"message":"Welcome! Reply HELP for assistance."}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'SMS Delivery Confirmation', 'Confirm SMS delivery', 'sms', 'sms_delivered', '{}', 'add_tag', '{"tag_name":"sms-active"}', 0, 'minutes', 1, 5, NOW(), NOW()),
(1, 'SMS Reply Handler', 'Notify on SMS reply', 'sms', 'sms_replied', '{}', 'notify_user', '{"message":"SMS reply received"}', 0, 'minutes', 1, 9, NOW(), NOW()),
(1, 'SMS Stop Handler', 'Handle STOP keyword', 'sms', 'sms_opted_out', '{}', 'update_status', '{"status":"sms-opted-out"}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'SMS Link Click Follow-Up', 'Follow up on SMS link clicks', 'sms', 'sms_link_clicked', '{}', 'send_sms', '{"message":"Thanks for checking that out!"}', 1, 'hours', 1, 7, NOW(), NOW()),
(1, 'Missed Call Follow-Up', 'Send SMS after missed call', 'call', 'call_missed', '{}', 'send_sms', '{"message":"Sorry we missed your call!"}', 5, 'minutes', 1, 9, NOW(), NOW()),
(1, 'Voicemail Follow-Up', 'Email after leaving voicemail', 'call', 'call_voicemail', '{}', 'send_email', '{"subject":"We tried to reach you","template_id":null}', 30, 'minutes', 1, 7, NOW(), NOW()),
(1, 'Successful Call Tag', 'Tag contacts after successful call', 'call', 'call_completed', '{"duration_min":60}', 'add_tag', '{"tag_name":"called-successfully"}', 0, 'minutes', 1, 5, NOW(), NOW()),
(1, 'Interested Prospect Follow-Up', 'Follow up interested prospects', 'call', 'call_disposition', '{"disposition":"interested"}', 'send_email', '{"subject":"Great speaking with you!","template_id":null}', 1, 'hours', 1, 8, NOW(), NOW()),
(1, 'Not Interested Handler', 'Handle not interested disposition', 'call', 'call_disposition', '{"disposition":"not_interested"}', 'add_tag', '{"tag_name":"not-interested"}', 0, 'minutes', 1, 5, NOW(), NOW()),
(1, 'Callback Reminder', 'Remind about scheduled callbacks', 'call', 'call_disposition', '{"disposition":"callback"}', 'schedule_call', '{"title":"Scheduled Callback"}', 0, 'minutes', 1, 8, NOW(), NOW()),
(1, 'DNC Handler', 'Handle Do Not Call requests', 'call', 'call_disposition', '{"disposition":"dnc"}', 'update_status', '{"status":"do-not-call"}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Form Submission Welcome', 'Welcome new form submissions', 'form', 'form_submitted', '{}', 'send_email', '{"subject":"Thanks for reaching out!","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Lead Magnet Delivery', 'Deliver lead magnet after form submit', 'form', 'form_submitted', '{"form_type":"lead-magnet"}', 'send_email', '{"subject":"Your download is ready!","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Contact Form Notification', 'Notify team of contact form', 'form', 'form_submitted', '{"form_type":"contact"}', 'notify_user', '{"message":"New contact form submission"}', 0, 'minutes', 1, 9, NOW(), NOW()),
(1, 'Quote Request Follow-Up', 'Follow up on quote requests', 'form', 'form_submitted', '{"form_type":"quote"}', 'send_email', '{"subject":"Your quote request received","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Demo Request Handler', 'Handle demo requests', 'form', 'form_submitted', '{"form_type":"demo"}', 'send_email', '{"subject":"Your demo request - next steps","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Survey Completion Thanks', 'Thank contacts for completing surveys', 'form', 'form_submitted', '{"form_type":"survey"}', 'send_email', '{"subject":"Thanks for your feedback!","template_id":null}', 0, 'minutes', 1, 8, NOW(), NOW()),
(1, 'VIP Tag Welcome', 'Welcome new VIP contacts', 'email', 'tag_added', '{"tag":"vip"}', 'send_email', '{"subject":"Welcome to VIP status!","template_id":null}', 0, 'minutes', 1, 9, NOW(), NOW()),
(1, 'Hot Lead Alert', 'Alert sales team of hot leads', 'email', 'tag_added', '{"tag":"hot-lead"}', 'notify_user', '{"message":"Hot lead identified!"}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Trial Started Onboarding', 'Start onboarding for trial users', 'email', 'tag_added', '{"tag":"trial"}', 'send_email', '{"subject":"Welcome to your trial!","template_id":null}', 0, 'minutes', 1, 10, NOW(), NOW()),
(1, 'Customer Upgrade Celebration', 'Celebrate customer upgrades', 'email', 'tag_added', '{"tag":"upgraded"}', 'send_email', '{"subject":"Thanks for upgrading!","template_id":null}', 0, 'minutes', 1, 8, NOW(), NOW());
